

cc2_cn = {  # cc2_cn - Two Letter ISO Country Code to Country Name
    'AF': 'Afghanistan',
    'AX': 'Aland Islands',
    'AL': 'Albania',
    'DZ': 'Algeria',
    'AS': 'American Samoa',
    'AD': 'Andorra',
    'AO': 'Angola',
    'AI': 'Anguilla',
    'AQ': 'Antarctica',
    'AG': 'Antigua and Barbuda',
    'AR': 'Argentina',
    'AM': 'Armenia',
    'AW': 'Aruba',
    'AU': 'Australia',
    'AT': 'Austria',
    'AZ': 'Azerbaijan',
    'BS': 'Bahamas',
    'BH': 'Bahrain',
    'BD': 'Bangladesh',
    'BB': 'Barbados',
    'BY': 'Belarus',
    'BE': 'Belgium',
    'BZ': 'Belize',
    'BJ': 'Benin',
    'BM': 'Bermuda',
    'BT': 'Bhutan',
    'BO': 'Bolivia',
    'BA': 'Bosnia and Herzegovina',
    'BW': 'Botswana',
    'BV': 'Bouvet Island',
    'BR': 'Brazil',
    'VG': 'British Virgin Islands',
    'IO': 'British Indian Ocean Territory',
    'BN': 'Brunei Darussalam',
    'BG': 'Bulgaria',
    'BF': 'Burkina Faso',
    'BI': 'Burundi',
    'KH': 'Cambodia',
    'CM': 'Cameroon',
    'CA': 'Canada',
    'CV': 'Cape Verde',
    'KY': 'Cayman Islands',
    'CF': 'Central African Republic',
    'TD': 'Chad',
    'CL': 'Chile',
    'CN': 'China',
    'HK': 'Hong Kong, Special Administrative Region of China',
    'MO': 'Macao, Special Administrative Region of China',
    'CX': 'Christmas Island',
    'CC': 'Cocos (Keeling) Islands',
    'CO': 'Colombia',
    'KM': 'Comoros',
    'CG': 'Congo (Brazzaville)',
    'CD': 'Congo, Democratic Republic of the',
    'CK': 'Cook Islands',
    'CR': 'Costa Rica',
    'CI': 'Cote d\'Ivoire',
    'HR': 'Croatia',
    'CU': 'Cuba',
    'CY': 'Cyprus',
    'CZ': 'Czech Republic',
    'DK': 'Denmark',
    'DJ': 'Djibouti',
    'DM': 'Dominica',
    'DO': 'Dominican Republic',
    'EC': 'Ecuador',
    'EG': 'Egypt',
    'SV': 'El Salvador',
    'GQ': 'Equatorial Guinea',
    'ER': 'Eritrea',
    'EE': 'Estonia',
    'ET': 'Ethiopia',
    'FK': 'Falkland Islands (Malvinas)',
    'FO': 'Faroe Islands',
    'FJ': 'Fiji',
    'FI': 'Finland',
    'FR': 'France',
    'GF': 'French Guiana',
    'PF': 'French Polynesia',
    'TF': 'French Southern Territories',
    'GA': 'Gabon',
    'GM': 'Gambia',
    'GE': 'Georgia',
    'DE': 'Germany',
    'GH': 'Ghana',
    'GI': 'Gibraltar',
    'GR': 'Greece',
    'GL': 'Greenland',
    'GD': 'Grenada',
    'GP': 'Guadeloupe',
    'GU': 'Guam',
    'GT': 'Guatemala',
    'GG': 'Guernsey',
    'GN': 'Guinea',
    'GW': 'Guinea-Bissau',
    'GY': 'Guyana',
    'HT': 'Haiti',
    'HM': 'Heard Island and Mcdonald Islands',
    'VA': 'Holy See (Vatican City State)',
    'HN': 'Honduras',
    'HU': 'Hungary',
    'IS': 'Iceland',
    'IN': 'India',
    'ID': 'Indonesia',
    'IR': 'Iran, Islamic Republic of',
    'IQ': 'Iraq',
    'IE': 'Ireland',
    'IM': 'Isle of Man',
    'IL': 'Israel',
    'IT': 'Italy',
    'JM': 'Jamaica',
    'JP': 'Japan',
    'JE': 'Jersey',
    'JO': 'Jordan',
    'KZ': 'Kazakhstan',
    'KE': 'Kenya',
    'KI': 'Kiribati',
    'KP': 'Korea, Democratic People\'s Republic of',
    'KR': 'Korea, Republic of',
    'KW': 'Kuwait',
    'KG': 'Kyrgyzstan',
    'LA': 'Lao PDR',
    'LV': 'Latvia',
    'LB': 'Lebanon',
    'LS': 'Lesotho',
    'LR': 'Liberia',
    'LY': 'Libya',
    'LI': 'Liechtenstein',
    'LT': 'Lithuania',
    'LU': 'Luxembourg',
    'MK': 'Macedonia, Republic of',
    'MG': 'Madagascar',
    'MW': 'Malawi',
    'MY': 'Malaysia',
    'MV': 'Maldives',
    'ML': 'Mali',
    'MT': 'Malta',
    'MH': 'Marshall Islands',
    'MQ': 'Martinique',
    'MR': 'Mauritania',
    'MU': 'Mauritius',
    'YT': 'Mayotte',
    'MX': 'Mexico',
    'FM': 'Micronesia, Federated States of',
    'MD': 'Moldova',
    'MC': 'Monaco',
    'MN': 'Mongolia',
    'ME': 'Montenegro',
    'MS': 'Montserrat',
    'MA': 'Morocco',
    'MZ': 'Mozambique',
    'MM': 'Myanmar',
    'NA': 'Namibia',
    'NR': 'Nauru',
    'NP': 'Nepal',
    'NL': 'Netherlands',
    'AN': 'Netherlands Antilles',
    'NC': 'New Caledonia',
    'NZ': 'New Zealand',
    'NI': 'Nicaragua',
    'NE': 'Niger',
    'NG': 'Nigeria',
    'NU': 'Niue',
    'NF': 'Norfolk Island',
    'MP': 'Northern Mariana Islands',
    'NO': 'Norway',
    'OM': 'Oman',
    'PK': 'Pakistan',
    'PW': 'Palau',
    'PS': 'Palestinian Territory, Occupied',
    'PA': 'Panama',
    'PG': 'Papua New Guinea',
    'PY': 'Paraguay',
    'PE': 'Peru',
    'PH': 'Philippines',
    'PN': 'Pitcairn',
    'PL': 'Poland',
    'PT': 'Portugal',
    'PR': 'Puerto Rico',
    'QA': 'Qatar',
    'RE': 'Reunion',
    'RO': 'Romania',
    'RU': 'Russian Federation',
    'RW': 'Rwanda',
    'BL': 'Saint-Barthelemy',
    'SH': 'Saint Helena',
    'KN': 'Saint Kitts and Nevis',
    'LC': 'Saint Lucia',
    'MF': 'Saint-Martin (French part)',
    'PM': 'Saint Pierre and Miquelon',
    'VC': 'Saint Vincent and Grenadines',
    'WS': 'Samoa',
    'SM': 'San Marino',
    'ST': 'Sao Tome and Principe',
    'SA': 'Saudi Arabia',
    'SN': 'Senegal',
    'RS': 'Serbia',
    'SC': 'Seychelles',
    'SL': 'Sierra Leone',
    'SG': 'Singapore',
    'SK': 'Slovakia',
    'SI': 'Slovenia',
    'SB': 'Solomon Islands',
    'SO': 'Somalia',
    'ZA': 'South Africa',
    'GS': 'South Georgia and the South Sandwich Islands',
    'SS': 'South Sudan',
    'ES': 'Spain',
    'LK': 'Sri Lanka',
    'SD': 'Sudan',
    'SR': 'Suriname',
    'SJ': 'Svalbard and Jan Mayen Islands',
    'SZ': 'Swaziland',
    'SE': 'Sweden',
    'CH': 'Switzerland',
    'SY': 'Syrian Arab Republic (Syria)',
    'TW': 'Taiwan, Republic of China',
    'TJ': 'Tajikistan',
    'TZ': 'Tanzania, United Republic of',
    'TH': 'Thailand',
    'TL': 'Timor-Leste',
    'TG': 'Togo',
    'TK': 'Tokelau',
    'TO': 'Tonga',
    'TT': 'Trinidad and Tobago',
    'TN': 'Tunisia',
    'TR': 'Turkey',
    'TM': 'Turkmenistan',
    'TC': 'Turks and Caicos Islands',
    'TV': 'Tuvalu',
    'UG': 'Uganda',
    'UA': 'Ukraine',
    'AE': 'United Arab Emirates',
    'GB': 'United Kingdom',
    'US': 'United States of America',
    'UM': 'United States Minor Outlying Islands',
    'UY': 'Uruguay',
    'UZ': 'Uzbekistan',
    'VU': 'Vanuatu',
    'VE': 'Venezuela (Bolivarian Republic of)',
    'VN': 'Viet Nam',
    'VI': 'Virgin Islands, US',
    'WF': 'Wallis and Futuna Islands',
    'EH': 'Western Sahara',
    'YE': 'Yemen',
    'ZM': 'Zambia',
    'ZW': 'Zimbabwe'
}

cc3_cn = {  # cc3_cn - Three Letter ISO Country Code to Country Name
    'AFG': 'Afghanistan',
    'ALA': 'Aland Islands',
    'ALB': 'Albania',
    'DZA': 'Algeria',
    'ASM': 'American Samoa',
    'AND': 'Andorra',
    'AGO': 'Angola',
    'AIA': 'Anguilla',
    'ATA': 'Antarctica',
    'ATG': 'Antigua and Barbuda',
    'ARG': 'Argentina',
    'ARM': 'Armenia',
    'ABW': 'Aruba',
    'AUS': 'Australia',
    'AUT': 'Austria',
    'AZE': 'Azerbaijan',
    'BHS': 'Bahamas',
    'BHR': 'Bahrain',
    'BGD': 'Bangladesh',
    'BRB': 'Barbados',
    'BLR': 'Belarus',
    'BEL': 'Belgium',
    'BLZ': 'Belize',
    'BEN': 'Benin',
    'BMU': 'Bermuda',
    'BTN': 'Bhutan',
    'BOL': 'Bolivia',
    'BIH': 'Bosnia and Herzegovina',
    'BWA': 'Botswana',
    'BVT': 'Bouvet Island',
    'BRA': 'Brazil',
    'VGB': 'British Virgin Islands',
    'IOT': 'British Indian Ocean Territory',
    'BRN': 'Brunei Darussalam',
    'BGR': 'Bulgaria',
    'BFA': 'Burkina Faso',
    'BDI': 'Burundi',
    'KHM': 'Cambodia',
    'CMR': 'Cameroon',
    'CAN': 'Canada',
    'CPV': 'Cape Verde',
    'CYM': 'Cayman Islands',
    'CAF': 'Central African Republic',
    'TCD': 'Chad',
    'CHL': 'Chile',
    'CHN': 'China',
    'HKG': 'Hong Kong, Special Administrative Region of China',
    'MAC': 'Macao, Special Administrative Region of China',
    'CXR': 'Christmas Island',
    'CCK': 'Cocos (Keeling) Islands',
    'COL': 'Colombia',
    'COM': 'Comoros',
    'COG': 'Congo (Brazzaville)',
    'COD': 'Congo, Democratic Republic of the',
    'COK': 'Cook Islands',
    'CRI': 'Costa Rica',
    'CIV': 'Cote d\'Ivoire',
    'HRV': 'Croatia',
    'CUB': 'Cuba',
    'CYP': 'Cyprus',
    'CZE': 'Czech Republic',
    'DNK': 'Denmark',
    'DJI': 'Djibouti',
    'DMA': 'Dominica',
    'DOM': 'Dominican Republic',
    'ECU': 'Ecuador',
    'EGY': 'Egypt',
    'SLV': 'El Salvador',
    'GNQ': 'Equatorial Guinea',
    'ERI': 'Eritrea',
    'EST': 'Estonia',
    'ETH': 'Ethiopia',
    'FLK': 'Falkland Islands (Malvinas)',
    'FRO': 'Faroe Islands',
    'FJI': 'Fiji',
    'FIN': 'Finland',
    'FRA': 'France',
    'GUF': 'French Guiana',
    'PYF': 'French Polynesia',
    'ATF': 'French Southern Territories',
    'GAB': 'Gabon',
    'GMB': 'Gambia',
    'GEO': 'Georgia',
    'DEU': 'Germany',
    'GHA': 'Ghana',
    'GIB': 'Gibraltar',
    'GRC': 'Greece',
    'GRL': 'Greenland',
    'GRD': 'Grenada',
    'GLP': 'Guadeloupe',
    'GUM': 'Guam',
    'GTM': 'Guatemala',
    'GGY': 'Guernsey',
    'GIN': 'Guinea',
    'GNB': 'Guinea-Bissau',
    'GUY': 'Guyana',
    'HTI': 'Haiti',
    'HMD': 'Heard Island and Mcdonald Islands',
    'VAT': 'Holy See (Vatican City State)',
    'HND': 'Honduras',
    'HUN': 'Hungary',
    'ISL': 'Iceland',
    'IND': 'India',
    'IDN': 'Indonesia',
    'IRN': 'Iran, Islamic Republic of',
    'IRQ': 'Iraq',
    'IRL': 'Ireland',
    'IMN': 'Isle of Man',
    'ISR': 'Israel',
    'ITA': 'Italy',
    'JAM': 'Jamaica',
    'JPN': 'Japan',
    'JEY': 'Jersey',
    'JOR': 'Jordan',
    'KAZ': 'Kazakhstan',
    'KEN': 'Kenya',
    'KIR': 'Kiribati',
    'PRK': 'Korea, Democratic People\'s Republic of',
    'KOR': 'Korea, Republic of',
    'KWT': 'Kuwait',
    'KGZ': 'Kyrgyzstan',
    'LAO': 'Lao PDR',
    'LVA': 'Latvia',
    'LBN': 'Lebanon',
    'LSO': 'Lesotho',
    'LBR': 'Liberia',
    'LBY': 'Libya',
    'LIE': 'Liechtenstein',
    'LTU': 'Lithuania',
    'LUX': 'Luxembourg',
    'MKD': 'Macedonia, Republic of',
    'MDG': 'Madagascar',
    'MWI': 'Malawi',
    'MYS': 'Malaysia',
    'MDV': 'Maldives',
    'MLI': 'Mali',
    'MLT': 'Malta',
    'MHL': 'Marshall Islands',
    'MTQ': 'Martinique',
    'MRT': 'Mauritania',
    'MUS': 'Mauritius',
    'MYT': 'Mayotte',
    'MEX': 'Mexico',
    'FSM': 'Micronesia, Federated States of',
    'MDA': 'Moldova',
    'MCO': 'Monaco',
    'MNG': 'Mongolia',
    'MNE': 'Montenegro',
    'MSR': 'Montserrat',
    'MAR': 'Morocco',
    'MOZ': 'Mozambique',
    'MMR': 'Myanmar',
    'NAM': 'Namibia',
    'NRU': 'Nauru',
    'NPL': 'Nepal',
    'NLD': 'Netherlands',
    'ANT': 'Netherlands Antilles',
    'NCL': 'New Caledonia',
    'NZL': 'New Zealand',
    'NIC': 'Nicaragua',
    'NER': 'Niger',
    'NGA': 'Nigeria',
    'NIU': 'Niue',
    'NFK': 'Norfolk Island',
    'MNP': 'Northern Mariana Islands',
    'NOR': 'Norway',
    'OMN': 'Oman',
    'PAK': 'Pakistan',
    'PLW': 'Palau',
    'PSE': 'Palestinian Territory, Occupied',
    'PAN': 'Panama',
    'PNG': 'Papua New Guinea',
    'PRY': 'Paraguay',
    'PER': 'Peru',
    'PHL': 'Philippines',
    'PCN': 'Pitcairn',
    'POL': 'Poland',
    'PRT': 'Portugal',
    'PRI': 'Puerto Rico',
    'QAT': 'Qatar',
    'REU': 'Reunion',
    'ROU': 'Romania',
    'RUS': 'Russian Federation',
    'RWA': 'Rwanda',
    'BLM': 'Saint-Barthelemy',
    'SHN': 'Saint Helena',
    'KNA': 'Saint Kitts and Nevis',
    'LCA': 'Saint Lucia',
    'MAF': 'Saint-Martin (French part)',
    'SPM': 'Saint Pierre and Miquelon',
    'VCT': 'Saint Vincent and Grenadines',
    'WSM': 'Samoa',
    'SMR': 'San Marino',
    'STP': 'Sao Tome and Principe',
    'SAU': 'Saudi Arabia',
    'SEN': 'Senegal',
    'SRB': 'Serbia',
    'SYC': 'Seychelles',
    'SLE': 'Sierra Leone',
    'SGP': 'Singapore',
    'SVK': 'Slovakia',
    'SVN': 'Slovenia',
    'SLB': 'Solomon Islands',
    'SOM': 'Somalia',
    'ZAF': 'South Africa',
    'SGS': 'South Georgia and the South Sandwich Islands',
    'SSD': 'South Sudan',
    'ESP': 'Spain',
    'LKA': 'Sri Lanka',
    'SDN': 'Sudan',
    'SUR': 'Suriname',
    'SJM': 'Svalbard and Jan Mayen Islands',
    'SWZ': 'Swaziland',
    'SWE': 'Sweden',
    'CHE': 'Switzerland',
    'SYR': 'Syrian Arab Republic (Syria)',
    'TWN': 'Taiwan, Republic of China',
    'TJK': 'Tajikistan',
    'TZA': 'Tanzania, United Republic of',
    'THA': 'Thailand',
    'TLS': 'Timor-Leste',
    'TGO': 'Togo',
    'TKL': 'Tokelau',
    'TON': 'Tonga',
    'TTO': 'Trinidad and Tobago',
    'TUN': 'Tunisia',
    'TUR': 'Turkey',
    'TKM': 'Turkmenistan',
    'TCA': 'Turks and Caicos Islands',
    'TUV': 'Tuvalu',
    'UGA': 'Uganda',
    'UKR': 'Ukraine',
    'ARE': 'United Arab Emirates',
    'GBR': 'United Kingdom',
    'USA': 'United States of America',
    'UMI': 'United States Minor Outlying Islands',
    'URY': 'Uruguay',
    'UZB': 'Uzbekistan',
    'VUT': 'Vanuatu',
    'VEN': 'Venezuela (Bolivarian Republic of)',
    'VNM': 'Viet Nam',
    'VIR': 'Virgin Islands, US',
    'WLF': 'Wallis and Futuna Islands',
    'ESH': 'Western Sahara',
    'YEM': 'Yemen',
    'ZMB': 'Zambia',
    'ZWE': 'Zimbabwe'
}

m49_cc = {  # cc3_cn - ISO Numeric Code UN M49 Numerical Code
    '4': 'Afghanistan',
    '248': 'Aland Islands',
    '8': 'Albania',
    '12': 'Algeria',
    '16': 'American Samoa',
    '20': 'Andorra',
    '24': 'Angola',
    '660': 'Anguilla',
    '10': 'Antarctica',
    '28': 'Antigua and Barbuda',
    '32': 'Argentina',
    '51': 'Armenia',
    '533': 'Aruba',
    '36': 'Australia',
    '40': 'Austria',
    '31': 'Azerbaijan',
    '44': 'Bahamas',
    '48': 'Bahrain',
    '50': 'Bangladesh',
    '52': 'Barbados',
    '112': 'Belarus',
    '56': 'Belgium',
    '84': 'Belize',
    '204': 'Benin',
    '60': 'Bermuda',
    '64': 'Bhutan',
    '68': 'Bolivia',
    '70': 'Bosnia and Herzegovina',
    '72': 'Botswana',
    '74': 'Bouvet Island',
    '76': 'Brazil',
    '92': 'British Virgin Islands',
    '86': 'British Indian Ocean Territory',
    '96': 'Brunei Darussalam',
    '100': 'Bulgaria',
    '854': 'Burkina Faso',
    '108': 'Burundi',
    '116': 'Cambodia',
    '120': 'Cameroon',
    '124': 'Canada',
    '132': 'Cape Verde',
    '136': 'Cayman Islands',
    '140': 'Central African Republic',
    '148': 'Chad',
    '152': 'Chile',
    '156': 'China',
    '344': 'Hong Kong, Special Administrative Region of China',
    '446': 'Macao, Special Administrative Region of China',
    '162': 'Christmas Island',
    '166': 'Cocos (Keeling) Islands',
    '170': 'Colombia',
    '174': 'Comoros',
    '178': 'Congo (Brazzaville)',
    '180': 'Congo, Democratic Republic of the',
    '184': 'Cook Islands',
    '188': 'Costa Rica',
    '384': 'Cote d\'Ivoire',
    '191': 'Croatia',
    '192': 'Cuba',
    '196': 'Cyprus',
    '203': 'Czech Republic',
    '208': 'Denmark',
    '262': 'Djibouti',
    '212': 'Dominica',
    '214': 'Dominican Republic',
    '218': 'Ecuador',
    '818': 'Egypt',
    '222': 'El Salvador',
    '226': 'Equatorial Guinea',
    '232': 'Eritrea',
    '233': 'Estonia',
    '231': 'Ethiopia',
    '238': 'Falkland Islands (Malvinas)',
    '234': 'Faroe Islands',
    '242': 'Fiji',
    '246': 'Finland',
    '250': 'France',
    '254': 'French Guiana',
    '258': 'French Polynesia',
    '260': 'French Southern Territories',
    '266': 'Gabon',
    '270': 'Gambia',
    '268': 'Georgia',
    '276': 'Germany',
    '288': 'Ghana',
    '292': 'Gibraltar',
    '300': 'Greece',
    '304': 'Greenland',
    '308': 'Grenada',
    '312': 'Guadeloupe',
    '316': 'Guam',
    '320': 'Guatemala',
    '831': 'Guernsey',
    '324': 'Guinea',
    '624': 'Guinea-Bissau',
    '328': 'Guyana',
    '332': 'Haiti',
    '334': 'Heard Island and Mcdonald Islands',
    '336': 'Holy See (Vatican City State)',
    '340': 'Honduras',
    '348': 'Hungary',
    '352': 'Iceland',
    '356': 'India',
    '360': 'Indonesia',
    '364': 'Iran, Islamic Republic of',
    '368': 'Iraq',
    '372': 'Ireland',
    '833': 'Isle of Man',
    '376': 'Israel',
    '380': 'Italy',
    '388': 'Jamaica',
    '392': 'Japan',
    '832': 'Jersey',
    '400': 'Jordan',
    '398': 'Kazakhstan',
    '404': 'Kenya',
    '296': 'Kiribati',
    '408': 'Korea, Democratic People\'s Republic of',
    '410': 'Korea, Republic of',
    '414': 'Kuwait',
    '417': 'Kyrgyzstan',
    '418': 'Lao PDR',
    '428': 'Latvia',
    '422': 'Lebanon',
    '426': 'Lesotho',
    '430': 'Liberia',
    '434': 'Libya',
    '438': 'Liechtenstein',
    '440': 'Lithuania',
    '442': 'Luxembourg',
    '807': 'Macedonia, Republic of',
    '450': 'Madagascar',
    '454': 'Malawi',
    '458': 'Malaysia',
    '462': 'Maldives',
    '466': 'Mali',
    '470': 'Malta',
    '584': 'Marshall Islands',
    '474': 'Martinique',
    '478': 'Mauritania',
    '480': 'Mauritius',
    '175': 'Mayotte',
    '484': 'Mexico',
    '583': 'Micronesia, Federated States of',
    '498': 'Moldova',
    '492': 'Monaco',
    '496': 'Mongolia',
    '499': 'Montenegro',
    '500': 'Montserrat',
    '504': 'Morocco',
    '508': 'Mozambique',
    '104': 'Myanmar',
    '516': 'Namibia',
    '520': 'Nauru',
    '524': 'Nepal',
    '528': 'Netherlands',
    '530': 'Netherlands Antilles',
    '540': 'New Caledonia',
    '554': 'New Zealand',
    '558': 'Nicaragua',
    '562': 'Niger',
    '566': 'Nigeria',
    '570': 'Niue',
    '574': 'Norfolk Island',
    '580': 'Northern Mariana Islands',
    '578': 'Norway',
    '512': 'Oman',
    '586': 'Pakistan',
    '585': 'Palau',
    '275': 'Palestinian Territory, Occupied',
    '591': 'Panama',
    '598': 'Papua New Guinea',
    '600': 'Paraguay',
    '604': 'Peru',
    '608': 'Philippines',
    '612': 'Pitcairn',
    '616': 'Poland',
    '620': 'Portugal',
    '630': 'Puerto Rico',
    '634': 'Qatar',
    '638': 'Reunion',
    '642': 'Romania',
    '643': 'Russian Federation',
    '646': 'Rwanda',
    '652': 'Saint-Barthelemy',
    '654': 'Saint Helena',
    '659': 'Saint Kitts and Nevis',
    '662': 'Saint Lucia',
    '663': 'Saint-Martin (French part)',
    '666': 'Saint Pierre and Miquelon',
    '670': 'Saint Vincent and Grenadines',
    '882': 'Samoa',
    '674': 'San Marino',
    '678': 'Sao Tome and Principe',
    '682': 'Saudi Arabia',
    '686': 'Senegal',
    '688': 'Serbia',
    '690': 'Seychelles',
    '694': 'Sierra Leone',
    '702': 'Singapore',
    '703': 'Slovakia',
    '705': 'Slovenia',
    '90': 'Solomon Islands',
    '706': 'Somalia',
    '710': 'South Africa',
    '239': 'South Georgia and the South Sandwich Islands',
    '728': 'South Sudan',
    '724': 'Spain',
    '144': 'Sri Lanka',
    '736': 'Sudan',
    '740': 'Suriname',
    '744': 'Svalbard and Jan Mayen Islands',
    '748': 'Swaziland',
    '752': 'Sweden',
    '756': 'Switzerland',
    '760': 'Syrian Arab Republic (Syria)',
    '158': 'Taiwan, Republic of China',
    '762': 'Tajikistan',
    '834': 'Tanzania, United Republic of',
    '764': 'Thailand',
    '626': 'Timor-Leste',
    '768': 'Togo',
    '772': 'Tokelau',
    '776': 'Tonga',
    '780': 'Trinidad and Tobago',
    '788': 'Tunisia',
    '792': 'Turkey',
    '795': 'Turkmenistan',
    '796': 'Turks and Caicos Islands',
    '798': 'Tuvalu',
    '800': 'Uganda',
    '804': 'Ukraine',
    '784': 'United Arab Emirates',
    '826': 'United Kingdom',
    '840': 'United States of America',
    '581': 'United States Minor Outlying Islands',
    '858': 'Uruguay',
    '860': 'Uzbekistan',
    '548': 'Vanuatu',
    '862': 'Venezuela (Bolivarian Republic of)',
    '704': 'Viet Nam',
    '850': 'Virgin Islands, US',
    '876': 'Wallis and Futuna Islands',
    '732': 'Western Sahara',
    '887': 'Yemen',
    '894': 'Zambia',
    '716': 'Zimbabwe'
}
